### ISSUE TITLE
SD-JWT VC Chaining / Delegation?

### ISSUE THREAD

**Issue by c2bo** [oauth-wg/oauth-sd-jwt-vc#208] opened 2024-02-10 14:03 UTC
I've been getting increasing amounts of questions about delegation / chaining with sd-jwts (and mdoc). Especially delegation seems to be a topic that people are starting to wonder about with cases like a person acting on behalf of another person in certain scopes (e.g., tax consultant accessing a system on your behalf). 

My naive thought was that this could be done similarly to how the x5c header parameter currently works: Introduce a new header parameter that contains an sd-jwt (including key binding jwt and relevant disclosures) where the chained sd-jwt is used to establish trust (via the original issuer) and resolve the key (confirmation claim) for signature validation. For implementations, this should not add too much effort as it would just be a recursive call to verify the contained sd-jwt vc.

I am not entirely sure it makes sense to bring in the additional complexity (and privacy concerns) but on the other hand I do see benefit in supporting some kind of credential chaining / delegation mechanism within the credential format itself. Do you think that this is something worth discussing and would this be the right spec to do so?

**Comment by peppelinux** [comment] 2024-02-10 14:24
good point, since the delegation in a SSI model must be perfomed by the end-user and not centralized in a credential issuer, the idea that came to my mind is to:

- define a credential type for this specific purpose
- define a data model for this specific purpose
- issue a self-issued token using SIOPv2 using a personal wallet
- encapsulate in this token two credential presentation (with the disclosure minimized for the purpose of the delegation):
  - the one of the delegator with the aud set to the final RP and the delegated subject
  - the one of the delegated with the aud set to the final RP and the delegator subject
- the token that encapsulate these two presented credentials with disclosure must be signed using the private key related to the public key to the delegator credential, contained in this token (providing the proof of possession)
- the delegator provides this token to the delegated

the RP that received this token from the delegated, in a VP_Token during a presentation, recognize the type and then the corresponding data model. 

Extracts the two VC, evaluates the trust with both their issuers, evaluates the pop of the delegator, evaluates the pop of the delegator in the presentation, then authenticates/grants the delegated.

how these tokens can be exchanges should be further defined. In my assumoption cannot exist delegation for any RP, each delegation must be configured with a specific RP or a set of RPs (aud). the chained approach is nested using attribute and cryptografic bindinds.

to be continued ... :-)

**Comment by awoie** [comment] 2024-04-30 17:17
I agree with @peppelinux that this is not an SD-JWT VC spec question, it is a credential type question. IMO, this is out of scope of this spec.

**Comment by bc-pi** [comment] 2024-04-30 18:01
I would concur that this is beyond the scope of this spec.

**Comment by c2bo** [comment] 2024-05-07 14:26
I generally agree (which is also why I was unsure if I should raise this issue here), but that poses the question: Where would we propose a structure for this? Imho it would make sense to propose a general approach that is shared at least to some degree between different credential types.

**Comment by peppelinux** [comment] 2024-05-08 13:12
@c2bo a brand new draft should born explaining a "shared credential", where the holder of this shared credential presents the enveloped credential(s) is a brand new type of credential specifically born for this use case

I share to you my Car key credential (shortlived), you present this to my Car and drive it untill the credential is valid (unexpired/revoked).

this - definitively - exalts concepts of sharing vs. presentation and also delegated presentation.

**Comment by awoie** [comment] 2024-05-24 10:03
> @c2bo a brand new draft should born explaining a "shared credential", where the holder of this shared credential presents the enveloped credential(s) is a brand new type of credential specifically born for this use case
> 
> I share to you my Car key credential (shortlived), you present this to my Car and drive it untill the credential is valid (unexpired/revoked).
> 
> this - definitively - exalts concepts of sharing vs. presentation and also delegated presentation.

I would expect those things to be very ecosystem (EUDIW) or even domain-specific (car vendors). However, SD-JWT VC is extensible by design and can include any sort of claims and even another PID credential as a claim (if needed), so I believe this use case is supported in general but out-of-scope of this specification.

@c2bo @peppelinux Marking this as pending close for one week and then close if no activity.

**Comment by c2bo** [comment] 2024-05-24 11:54
I agree that this is likely going to be somewhat ecosystem specific, but I do believe one place to create an "example" / best practice could still help though. I agree that this draft is probably not the right place though -> let's figure out where this would fit.

**Comment by c2bo** [comment] 2024-06-03 11:48
I am not aware of a somewhat complete list of use-cases. The main use-cases that I have seen mentioned and been asked about (and also ones that we are most interested in) goes into the direction of Power of Attorney. Acting on behalf of another entity via some sort of signed credential/document.

Should we close this issue here and figure out a better place to have this discussion?

**Comment by awoie** [comment] 2024-06-11 17:56
Closing now since it is out of scope.

**Closed by awoie** 2024-06-11 17:56 UTC
Labels: pending close
