### ISSUE TITLE
What is the relationship between verifiable presentations and combined format for presentation?

### ISSUE THREAD

**Issue by andresuribe87** [oauth-wg/oauth-sd-jwt-vc#115] opened 2023-05-26 21:51 UTC
My  expectation was that the SD-JWT's combined format for presentation would be used inside a verifiable presentation. Something similar to the example below
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "urn:uuid:3978344f-8596-4c3a-a978-8fcaba3903c5",
  "type": ["VerifiablePresentation"],
  "verifiableCredential": [{
    "type": "SD-JWT Presentation",
    "combinedFormat": "XXX.XXX.XXX~YYY~ZZZ"
  }]
}
```

I'm curious whether this was considered. If so, it would be nice to add a section on that to the spec on the relationship.

**Comment by danielfett** [comment] 2023-08-16 08:15
This spec defines its own format for verifiable presentations without a focus on being compatible to the W3C format. It may be possible to envelope the presentation format as shown in your example, but that would not be defined by this specification.

**Comment by awoie** [comment] 2023-09-21 09:31
Duplicate of #113

**Closed by awoie** 2023-09-21 09:31 UTC
